blog/urls.py
from django.urls import path
from . import views



urlpatterns = [

path('', views.blog, name='havaso-blog'),

]

newsletter/urls.py
from surlex.dj import surl

from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionView,
)

urlpatterns = [
    # Newsletter list and detail view
    surl('^$', NewsletterListView.as_view(), name='newsletter_list'),
    surl(
        '^<newsletter_slug:s>/$',
        NewsletterDetailView.as_view(), name='newsletter_detail'
    ),

    # Action request views
    surl(
        '^<newsletter_slug:s>/subscribe/$',
        SubscribeRequestView.as_view(),
        name='newsletter_subscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/subscribe/confirm/$',
        SubscribeRequestView.as_view(confirm=True),
        name='newsletter_subscribe_confirm'
    ),
    surl(
        '^<newsletter_slug:s>/update/$',
        UpdateRequestView.as_view(),
        name='newsletter_update_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/$',
        UnsubscribeRequestView.as_view(),
        name='newsletter_unsubscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/confirm/$',
        UnsubscribeRequestView.as_view(confirm=True),
        name='newsletter_unsubscribe_confirm'
    ),

    # Activation email sent view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'email-sent/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='newsletter_activation_email_sent'),

    # Action confirmation views
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update_activate'
    ),
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update'
    ),

    # Action activation completed view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'activation-completed/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_activated.html'
        ),
        name='newsletter_action_activated'),

    # Archive views
    surl(
        '^<newsletter_slug:s>/archive/<year:Y>/<month:m>/<day:d>/<slug:s>/$',
        SubmissionArchiveDetailView.as_view(), name='newsletter_archive_detail'
    ),
    surl(
        '^<newsletter_slug:s>/archive/$',
        SubmissionArchiveIndexView.as_view(), name='newsletter_archive'
    ),
]

wishlist/urls.py
from django.urls import path
from . import views



urlpatterns = [
path('', views.wishlist, name='wishlist'),
path('add/', views.add, name='addwishlist'),
path('view/', views.viewwishlist, name='viewwishlist'),
path('emailwishlist/', views.sendwishlistemail, name='sendemailwishlist'),
path('remove/', views.remove_jar_from_wish_list, name='remove')
]

wishlist/models.py
from django.db import models
from autoslug import AutoSlugField
from album.models import Jar
import string
import random
from django.utils import timezone


# Create your models here.

def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class SentWishlist(models.Model):
    email = models.CharField(max_length=100, blank=True, default=None)
    wishlistedjars = models.ManyToManyField(Jar, blank=True, default=None)
    url_ref = AutoSlugField(default=rand_slug(), unique=True)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.email

newsletter/forms.py
from django import forms
from django.forms.utils import ValidationError
from django.utils.translation import ugettext_lazy as _
import logging
from .models import Subscription
from .validators import validate_email_nouser


class NewsletterForm(forms.ModelForm):
    """ This is the base class for all forms managing subscriptions. """

    class Meta:
        model = Subscription
        fields = ('name_field', 'email_field')

    def __init__(self, *args, **kwargs):

        assert 'newsletter' in kwargs, 'No newsletter specified'

        newsletter = kwargs.pop('newsletter')

        if 'ip' in kwargs:
            ip = kwargs['ip']
            del kwargs['ip']
        else:
            ip = None

        super(NewsletterForm, self).__init__(*args, **kwargs)

        self.instance.newsletter = newsletter

        if ip:
            self.instance.ip = ip


class SubscribeRequestForm(NewsletterForm):
    """
    Request subscription to the newsletter. Will result in an activation email
    being sent with a link where one can edit, confirm and activate one's
    subscription.
    """

    email_field = forms.EmailField(
        label=_("e-mail"), validators=[validate_email_nouser]
    )

    def clean_email_field(self):
        data = self.cleaned_data['email_field']
        # Check whether we have already been subscribed to
        try:
            subscription = Subscription.objects.get(
                email_field__exact=data,
                newsletter=self.instance.newsletter
            )

            logging.info(subscription)

            if subscription.subscribed and not subscription.unsubscribed:
                logging.info("Email was already subscribed")
                raise ValidationError(
                    _("Your e-mail address has already been subscribed to.")
                )
            else:
                self.instance = subscription
                logging.info("Email subscribed!")

            self.instance = subscription

        except Subscription.DoesNotExist:
            pass

        return data


class UpdateRequestForm(NewsletterForm):
    """
    Request updating or activating subscription. Will result in an activation
    email being sent.
    """

    email_field = forms.EmailField(
        label=_("e-mail"), validators=[validate_email_nouser]
    )

    class Meta(NewsletterForm.Meta):
        fields = ('email_field',)

    def clean(self):
        if not self.instance.subscribed:
            raise ValidationError(
                _("This subscription has not yet been activated.")
            )

        return super(UpdateRequestForm, self).clean()

    def clean_email_field(self):
        data = self.cleaned_data['email_field']

        # Set our instance on the basis of the email field, or raise
        # a validationerror
        try:
            self.instance = Subscription.objects.get(
                newsletter=self.instance.newsletter,
                email_field__exact=data
            )

        except Subscription.DoesNotExist:
                raise ValidationError(
                    _("This e-mail address has not been subscribed to.")
                )

        return data


class UnsubscribeRequestForm(UpdateRequestForm):
    """
    Similar to previous form but checks if we have not
    already been unsubscribed.
    """

    def clean(self):
        if self.instance.unsubscribed:
            raise ValidationError(
                _("This subscription has already been unsubscribed from.")
            )

        return super(UnsubscribeRequestForm, self).clean()


class UpdateForm(NewsletterForm):
    """
    This form allows one to actually update to or unsubscribe from the
    newsletter. To do this, a correct activation code is required.
    """

    email_field = forms.EmailField(
        label=_("e-mail"), validators=[validate_email_nouser], disabled=True
    )

    def clean_user_activation_code(self):
        data = self.cleaned_data['user_activation_code']

        if data != self.instance.activation_code:
            raise ValidationError(
                _('The validation code supplied by you does not match.')
            )

        return data

    user_activation_code = forms.CharField(
        label=_("Activation code"), max_length=40
    )


class UserUpdateForm(forms.ModelForm):
    """
    Form for updating subscription information/unsubscribing as a logged-in
    user.
    """

    class Meta:
        model = Subscription
        fields = ('subscribed',)
        # Newsletter here should become a read only field,
        # once this is supported by Django.

        # For now, use a hidden field.
        hidden_fields = ('newsletter',)

wishlist/views.py
from __future__ import absolute_import, unicode_literals
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from album.models import Jar, Decorator
from .models import SentWishlist
from django.core import serializers
import json
from blog.models import Post
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.template.defaulttags import register
from home.views import check_set_session
from django.contrib.sites.shortcuts import get_current_site
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime, timezone
from django.contrib.sites.models import Site
from django.core import mail

website = Site.objects.get_current()

@csrf_exempt
def add(request):
    print(request.session['session'])
    if request.method == "POST" and request.POST.get("jar"):
        print(request.POST.get("jar"))
        status = request.POST.get("jar")
        if status not in request.session['session']['products']:
            request.session['session']['products'].append(status)
            request.session.modified = True
    else:
        if request.POST.get("buyjar"):
            jar_number = request.POST.get("buyjar", )
            request.session['session']['buy'] = jar_number
            request.session.modified = True

    return JsonResponse("Type in a Jar name", safe=False)


@csrf_exempt
def remove_jar_from_wish_list(request):
    print(request.session['session'])
    if request.POST.get("removejar"):
        jar_number = request.POST.get("removejar", )
        request.session['session']['products'].remove(jar_number)
        request.session.modified = True
    return JsonResponse("Jar Removed", safe=False)


def viewwishlist(request):
    wish_listed_items_detail_list = []
    output = {}
    if request.method == "GET":
        try:
            wish_listed_items = request.session.get('session')['products']

            for item in wish_listed_items:
                wish_listed_items_details = Jar.objects.select_related('decorator').filter(jar_number__iexact=item)
                wish_listed_items_detail_list.append(wish_listed_items_details)
            i = 0
            for item in wish_listed_items_detail_list:
                # STRING
                data = serializers.serialize('json', item)
                # List and inside dictionary
                d = json.loads(data)
                # Append only dictionary to a list with dictionary
                for dec in item:
                    decorator = dec.decorator
                    d[0]['fields']['decorator'] = str(decorator)
                output[i] = d[0]
                i += 1
            d = json.dumps([output])

        except:
            d = None
    return HttpResponse(d, content_type='application/json')


def sendwishlistemail(request):
    email = request.POST.get("mail")
    jars_objects = []
    wish_listed_items = request.session.get('session')['products']
    if len(wish_listed_items) is not 0:
        print(email)
        for jar in wish_listed_items:
            jars_objects.append(Jar.objects.get(jar_number=jar))

        a = SentWishlist(email=email)
        a.save()
        a.wishlistedjars.set(jars_objects)

        subject, from_email = 'Your Medicine Jar Wish List', 'support@havaso.com',
        link = str(website) + '/wishlist/?wishlist=' + str(a.url_ref)
        html_content = render_to_string('wishlist/mail.html', {'link': link})  # render with dynamic value
        plain_message = strip_tags(html_content)
        # create the email, and attach the HTML version as well.
        mail.send_mail(subject, plain_message, from_email, [email], html_message=html_content)


        return HttpResponse("Done!")
    else:
        return HttpResponse("Empty")


def wishlist(request):
    @register.filter
    def get_item(dictionary, key):
        return dictionary.get(pk=key)

    check_set_session(request)
    wish_list_slug = request.GET.get("wishlist")
    wish_list_object = SentWishlist.objects.get(url_ref=wish_list_slug)
    decorators = Decorator.objects.filter(id__in=wish_list_object.wishlistedjars.values_list('decorator_id'))

    time_between_insertion = datetime.now(timezone.utc) - wish_list_object.date_created
    print(wish_list_object.wishlistedjars.values())
    if time_between_insertion.days < 30:
        context = {
            'decorator': decorators,
            'jars': wish_list_object.wishlistedjars.values(),
            'posts': Post.objects.all().order_by('-date_created')[:3],
        }
    else:
        context = {
            'decorator': "",
            'jars': "Expired",
            'posts': Post.objects.all().order_by('-date_created')[:3],
        }

    return render(request, 'wishlist/wishlist.html', context)

wishlist/templates/wishlist/added-to-wishlist-modal.html
<!-- Modal -->
<div class="modal fade" id="wishlist" tabindex="-1" role="dialog" aria-labelledby="wishlist" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Added to your wishlist!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-8"><img src="/media/{{ jar.0.jar_image }}" height="425px"
                                                           width="425px" alt="" class="mr-2 jar-img-album"></div>
                                <div class="col-md-4 my-auto"><h3 class="jar-title">{{ jar.0.jar_title }}</h3>
                                    <h5>Description</h5>
                                    <p class="description">{{ jar.0.comment }}</p>
                                    <input type="submit" value="Go to my Wishlist"
                                           class="btn btn-large btn-outline-secondary btn-subscribe" data-toggle="modal"
                                           data-target="#wishlist"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <form class="form-inline sendwishlistemail" enctype="multipart/form-data" method="post"
                      action="/wishlist/emailwishlist/">
                    {% csrf_token %}
                    <div class="form-group m-2">
                        <input type="text" readonly class="form-control-plaintext" value="Email my wishlist.">
                    </div>
                    <div class="form-group mx-sm-3 m-2">
                        <input type="email" name="mail" required class="form-control" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-primary m-2">Send</button>
                    <button type="button" class="btn btn-secondary ml-1" data-dismiss="modal">Close</button>
                </form>
            </div>
            <div class="alert alert-primary wishlist-alert" hidden role="alert">
            </div>
        </div>
    </div>
</div>

wishlist/templates/wishlist/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<p>Hi,</p>

<p>You (or someone using your email address, so hopefully you) have made a wish list of potential Medicine Jars on our
    website. To review your wish list click here: <a href="http://{{ link }}"><strong>Go to Wishlist</strong></a>

<br>
<p> If you can't click the link above please copy this website: http://{{ link }} </p>
<br>
<p>The wish list is not meant as a means to reserve any jar. It’s possible one or more of the jars on your list will be
    sold by the time you revisit our website, so don’t wait to long to make your choice. You are free to make as many
    wish lists as you like and please feel free to forward your wish list to friends and family.</p>

<p>Your wish list will be accessible for 30 days. After those 30 days we will delete the list and the associated email. If
you haven’t subscribed to our newsletter yet, you can do so here: Link to subscription page. Subscribing means you to
    stay up to date about new arrivals in the store and additions to our <a href="http://havaso.com/blog/"><strong>Stories.</strong></a></p>
<p>
Regards,
</p>
<p>Gyske & Lilian</p>
<p>The CNG/havaso Team.</p>
</body>
</html>

wishlist/templates/wishlist/reminder_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<p>Hi,</p>

<p>A few weeks ago you (or someone using your email address) made a wish list of Medicine Jars on our website. We’d like to
    remind you this list will expire in 7 days.</p>

<p>To review your wish list click here: <a href="{{ link }}">Go to Wishlist</a></p>

<p>It’s possible one or more of the jars on your list are sold when you revisit our website. The wish list isn’t a
reservation list, but we may have added new jars, so make sure to visit the album too (link to album). You always can
make a new list (or even multiple). Want to share one or more jars with family? Simply forward them your wish list.</p>

<p>Unless you’ve subscribed to our newsletter you won’t hear from us again. We will remove your email address when we
    remove your wish list in 7 days. Until then you can see your wish list here:</p>

<p><a href="{{ link }}">Go to Wishlist</a></p>

<p>
Regards,
</p>
<p>Gyske & Lilian</p>
<p>The CNG/havaso Team.</p>
</body>
</html>

wishlist/templates/wishlist/wishlist.html
{% extends "home/base.html" %}

{% block content %}
<div class="container py-4">
    <div class="row">
        <div class="col-md-8">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Product</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody id="wishlisttable">
                        {% if jars != "Expired" %}
                        {% for jar in jars %}
                        <tr>
                            <td><img width="50px" src="/media/{{ jar.jar_image }}"></td>
                            <td> {{ jar.jar_name }} <p>Decorated by {{ decorator|get_item:jar.decorator_id}} </p></td>

                            <td class="text-right">
                                {% if jar.jar_status == "Sold" %}
                                <button value="{{ jar.jar_number }}" disabled class="btn btn-sm btn-dark">Sold</button>
                                {% else %}
                                <button value="{{ jar.jar_number }}" class="btn btn-sm btn-success buyjar">Buy</button>
                                {% endif %}
                            </td>
                        </tr>
                          </tbody>
                    </table>
                        {% endfor %}
                        {% else %}
                        </tbody>
                    </table>


                    <h1>This wish list has expired!</h1>
                    {% endif %}
                </div>
            </div>


        </div>


        <div class="col-md-4">
            <div class="thumbnail center well well-sm text-center">
                <h2>Newsletter</h2>
                <p>Subscribe to our weekly Newsletter and stay tuned.</p>

                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-light" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}


                <form enctype="multipart/form-data" method="post" action="/newsletter/newsletter/subscribe/">
                    {% csrf_token %}
                    <input type="email" class="form-control" name="email_field" required="" placeholder="Email"
                           id="id_email_field">
                    <button id="id_submit" name="submit" class="btn btn-large btn-outline-secondary btn-subscribe"
                            value="Subscribe" type="submit">Subscribe
                    </button>
                </form>
            </div>


            <div class="d-flex align-items-center  text-white-50 bg-purple rounded box-shadow">
                <img class="mr-3" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-outline.svg" alt=""
                     width="48" height="48">
                <div class="lh-100">
                    <h6 class="mb-0 text-white lh-100">Havaso</h6>

                </div>
            </div>

            {% include "blog/updates.html" with posts=posts %}


        </div>
    </div>


</div>


{% endblock %}

wishlist/templates/wishlist/wishlistmodal.html
<!-- Modal -->
<div class="modal fade" id="wishlist_items" tabindex="-1" role="dialog" aria-labelledby="wishlist" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">My wishlist!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="container mb-4">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col"></th>
                                        <th scope="col">Product</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody id="wishlisttable">


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">

                <form class="form-inline sendwishlistemail" enctype="multipart/form-data" method="post"
                      action="/wishlist/emailwishlist/">
                    {% csrf_token %}
                    <div class="form-group m-2">
                        <label for="staticEmail2" class="sr-only">Email</label>
                        <input type="text" readonly class="form-control-plaintext" id="staticEmail2" value="Email my wishlist.">
                    </div>
                    <div class="form-group mx-sm-3 m-2">
                        <label for="inputemail" class="sr-only">Email</label>
                        <input type="email" required name="mail" class="form-control" id="inputemail" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-primary m-2">Send</button>
                    <button type="button" class="btn btn-secondary ml-1" data-dismiss="modal">Close</button>
                </form>
            </div>
             <div class="alert alert-primary wishlist-alert" hidden role="alert">
             </div>
        </div>
    </div>
</div>